### ISSUE TITLE
404 on project page

### ISSUE THREAD

**Issue by jkempff** [ory-legacy/gitdeploy#20]
"404 page not found" at https://www.gitdeploy.io/

**Comment by arekkas** [comment]
Thanks, seems like the cluster got unstable once again..

**Comment by arekkas** [comment]
Upstream: #1654

**Comment by arekkas** [comment]
Took a while, but it's back ;)

**Comment by arekkas** [comment]
(once dns updates propagate)

**Comment by arekkas** [comment]
There still problem with the container, I hope I will find the root of the problem soon

**Comment by arekkas** [comment]
here we go :)a
